#include "StringUtils.h"

std::vector<std::string> StringUtils::split(std::string str, char splitBy)
{
	std::vector<std::string> splitVec;

	if(str.find(splitBy) == -1)
		return splitVec;

	unsigned int startIndex = 0;
	unsigned int len = (unsigned int)str.length();
	bool justNowOneStrSplitted = false;

	for(unsigned int i=0;i<len;i++)
	{
		if(justNowOneStrSplitted)
		{
			if(str[i] != splitBy)
			{
				justNowOneStrSplitted = false;
				startIndex = i;
			}
		}

		if(str[i] == splitBy || i == len-1)
		{
			justNowOneStrSplitted = true;

			if(i == len-1)
				splitVec.push_back(str.substr(startIndex, i-startIndex+1));
			else
				splitVec.push_back(str.substr(startIndex, i-startIndex));

			startIndex = i;
		}
	}
		
	return splitVec;
}

bool StringUtils::startsWith(std::string str, std::string checkStr)
{
	unsigned int strLen = (unsigned int)str.length();
	unsigned int checkStrLen = (unsigned int)checkStr.length();

	if(strLen < checkStrLen)
		return false;

	for(unsigned int i=0;i<checkStrLen;i++)
	{
		if(str[i] != checkStr[i])
			return false;
	}

	return true;
}

bool StringUtils::endsWith(std::string str, std::string checkStr)
{
	unsigned int strLen = (unsigned int)str.length();
	unsigned int checkStrLen = (unsigned int)checkStr.length();

	if(strLen < checkStrLen)
		return false;

	unsigned int strLastIndex = (unsigned int)(str.length()-1);
	unsigned int checkStrLastIndex = (unsigned int)(checkStr.length()-1);

	for(unsigned int i=0;i<checkStrLen;i++)
	{
		if(str[strLastIndex-i] != checkStr[checkStrLastIndex-i])
			return false;
	}

	return true;
}


float StringUtils::atof_naive(const char *p) {
	double r = 0.0;
	bool neg = false;
	if (*p == '-') {
		neg = true;
		++p;
	}
	while (*p >= '0' && *p <= '9') {
		r = (r*10.0) + (*p - '0');
		++p;
	}
	if (*p == '.') {
		double f = 0.0;
		int n = 0;
		++p;
		while (*p >= '0' && *p <= '9') {
			f = (f*10.0) + (*p - '0');
			++p;
			++n;
		}

		//TODO : check the performance difference between math funtion pow and std function pow
		r += f / std::pow(10.0, n);
	}
	if (neg) {
		r = -r;
	}

	//TODO: Casting double value to float for fixing warnings, but think of having another method specifically for double like atod 
	//TODO: Mainly using it in reading obj file, when we have to read more precision, we need double as data type.
	//TODO: Check the precision in stl file which generated by merge is sufficient for float or we need double as data type.
	return (float)r;
}

unsigned int StringUtils::atoi_naive(const char * p)
{
	unsigned int x = 0;
	while (*p) {
		x = x * 10 + (*p++ - '0');
	}
	return x;
}
